config:
  backend_uri: "http://backend.minikube.local"
image:
  repository: dahumbletechboy/shop-for-it
  tag: "2.0"
replicaCount: 2
service:
  type: ClusterIP
  port: 80
ingress:
  host: frontend.minikube.local