config:
  backend_uri: "http://backend.minikube.local"
image:
  repository: dahumbletechboy/shop-for-it
  tag: "2.1"
replicaCount: 1
service:
  type: LoadBalancer
  port: 80
ingress:
  host: frontend.minikube.local
resources:
  requests:
    memory: "600Mi"
    cpu: "250m"
  limits:
    memory: "800Mi"
    cpu: "500m"