secret:
  mongodb_uri: "LW4gbW9uZ29kYitzcnY6Ly9SYXNoZWVkOk1lY2hib3QxMjM0QGNsdXN0ZXIwLjM1NnFzOWIubW9uZ29kYi5uZXQvU2hvcC1Gb3ItSXQ/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Cg=="
image:
  repository: dahumbletechboy/shop-for-it-server
  tag: "2.1"
replicaCount: 1
service:
  type: LoadBalancer
  port: 80
ingress:
  host: backend.minikube.local
# resources:
#   requests:
#     memory: "512Mi"
#     cpu: "250m"
#   limits:
#     memory: "1Gi"
#     cpu: "500m"